/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import Almacen.JPNL_AlmacenMaqueta;
import Configuracion.JPNL_ConfiguracionMaqueta;
import Ventas.JPNL_VentasMaqueta;


/**
 *
 * @author DIEGO
 */
public class Ventana_Principal extends javax.swing.JFrame {
    
    private boolean minimizar = false;
    
    private JPNL_AlmacenMaqueta JPNL_Almacen;
    private JPNL_VentasMaqueta JPNL_Ventas;
    private JPNL_ConfiguracionMaqueta JPNL_Configuracion;
    
    public Ventana_Principal() {
        initComponents();
        
        thi
        
        this.JLBL_Panel.setText("C O N F I G U R A C I O N");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPNL_Fondo = new javax.swing.JPanel();
        JPNL_Menu = new javax.swing.JPanel();
        JBTN_Ventas = new rojeru_san.RSButtonRiple();
        JBTN_Almacen = new rojeru_san.RSButtonRiple();
        JBTN_Cajeros = new rojeru_san.RSButtonRiple();
        JBTN_Configuracion = new rojeru_san.RSButtonRiple();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        JPNL_Subfondo = new javax.swing.JPanel();
        JPNL_Cabecera = new javax.swing.JPanel();
        JBTN_Cerrar = new rojeru_san.rsbutton.RSButtonRoundEffect();
        JLBL_Panel = new javax.swing.JLabel();
        JBTN_Minimizar = new rojeru_san.rsbutton.RSButtonRoundEffect();
        JPN_DUsuario = new javax.swing.JPanel();
        JLBL_Nombre = new javax.swing.JLabel();
        JLBL_AsignarNombre = new javax.swing.JLabel();
        JLBL_AsignarTipo = new javax.swing.JLabel();
        JLBL_Tipo = new javax.swing.JLabel();
        JLBL_Id = new javax.swing.JLabel();
        JPNL_Slider = new rojerusan.RSPanelsSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        JPNL_Menu.setBackground(new java.awt.Color(34, 41, 50));

        JBTN_Ventas.setBackground(new java.awt.Color(34, 41, 50));
        JBTN_Ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Principal/Icono_Ventas.png"))); // NOI18N
        JBTN_Ventas.setText("VENTAS");
        JBTN_Ventas.setColorHover(new java.awt.Color(54, 63, 73));
        JBTN_Ventas.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        JBTN_Ventas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JBTN_Ventas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        JBTN_Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_VentasActionPerformed(evt);
            }
        });

        JBTN_Almacen.setBackground(new java.awt.Color(34, 41, 50));
        JBTN_Almacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Principal/Icono_Almacen.png"))); // NOI18N
        JBTN_Almacen.setText("ALMACEN");
        JBTN_Almacen.setColorHover(new java.awt.Color(54, 63, 73));
        JBTN_Almacen.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        JBTN_Almacen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JBTN_Almacen.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        JBTN_Almacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_AlmacenActionPerformed(evt);
            }
        });

        JBTN_Cajeros.setBackground(new java.awt.Color(34, 41, 50));
        JBTN_Cajeros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Principal/Icono_Cajeros.png"))); // NOI18N
        JBTN_Cajeros.setText("USUARIOS");
        JBTN_Cajeros.setColorHover(new java.awt.Color(54, 63, 73));
        JBTN_Cajeros.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        JBTN_Cajeros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JBTN_Cajeros.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        JBTN_Cajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_CajerosActionPerformed(evt);
            }
        });

        JBTN_Configuracion.setBackground(new java.awt.Color(34, 41, 50));
        JBTN_Configuracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Principal/Icono_Configuracion.png"))); // NOI18N
        JBTN_Configuracion.setText("CONFIGURACIÓN");
        JBTN_Configuracion.setColorHover(new java.awt.Color(54, 63, 73));
        JBTN_Configuracion.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        JBTN_Configuracion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JBTN_Configuracion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        JBTN_Configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_ConfiguracionActionPerformed(evt);
            }
        });

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/IMG/Principal/Logo_Banner.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JPNL_MenuLayout = new javax.swing.GroupLayout(JPNL_Menu);
        JPNL_Menu.setLayout(JPNL_MenuLayout);
        JPNL_MenuLayout.setHorizontalGroup(
            JPNL_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JBTN_Ventas, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(JBTN_Almacen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JBTN_Cajeros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JBTN_Configuracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPNL_MenuLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(rSPanelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPNL_MenuLayout.setVerticalGroup(
            JPNL_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNL_MenuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(rSPanelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBTN_Ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBTN_Almacen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBTN_Cajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBTN_Configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
        );

        JPNL_Subfondo.setBackground(new java.awt.Color(255, 255, 255));

        JPNL_Cabecera.setBackground(new java.awt.Color(255, 255, 255));

        JBTN_Cerrar.setBackground(new java.awt.Color(255, 255, 255));
        JBTN_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Login/Icono_Cerrar.png"))); // NOI18N
        JBTN_Cerrar.setColorHover(new java.awt.Color(255, 255, 255));

        JLBL_Panel.setFont(new java.awt.Font("Aspergit", 1, 36)); // NOI18N
        JLBL_Panel.setForeground(new java.awt.Color(150, 150, 150));
        JLBL_Panel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBL_Panel.setText("VENTAS");

        JBTN_Minimizar.setBackground(new java.awt.Color(255, 255, 255));
        JBTN_Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Principal/Icono_Minimizar.png"))); // NOI18N
        JBTN_Minimizar.setColorHover(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout JPNL_CabeceraLayout = new javax.swing.GroupLayout(JPNL_Cabecera);
        JPNL_Cabecera.setLayout(JPNL_CabeceraLayout);
        JPNL_CabeceraLayout.setHorizontalGroup(
            JPNL_CabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNL_CabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBL_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBTN_Minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBTN_Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JPNL_CabeceraLayout.setVerticalGroup(
            JPNL_CabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNL_CabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPNL_CabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBTN_Minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLBL_Panel)
                    .addComponent(JBTN_Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPN_DUsuario.setBackground(new java.awt.Color(255, 255, 255));

        JLBL_Nombre.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        JLBL_Nombre.setForeground(new java.awt.Color(130, 130, 130));
        JLBL_Nombre.setText("NOMBRE:");

        JLBL_AsignarNombre.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        JLBL_AsignarNombre.setForeground(new java.awt.Color(130, 130, 130));
        JLBL_AsignarNombre.setText("ASIGNAR NOMBRE");

        JLBL_AsignarTipo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        JLBL_AsignarTipo.setForeground(new java.awt.Color(130, 130, 130));
        JLBL_AsignarTipo.setText("ASIGNAR TIPO");

        JLBL_Tipo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        JLBL_Tipo.setForeground(new java.awt.Color(130, 130, 130));
        JLBL_Tipo.setText("TIPO:");

        JLBL_Id.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        JLBL_Id.setForeground(new java.awt.Color(130, 130, 130));
        JLBL_Id.setText("ID");

        javax.swing.GroupLayout JPN_DUsuarioLayout = new javax.swing.GroupLayout(JPN_DUsuario);
        JPN_DUsuario.setLayout(JPN_DUsuarioLayout);
        JPN_DUsuarioLayout.setHorizontalGroup(
            JPN_DUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPN_DUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBL_Nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLBL_AsignarNombre)
                .addGap(14, 14, 14)
                .addComponent(JLBL_Tipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLBL_AsignarTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 577, Short.MAX_VALUE)
                .addComponent(JLBL_Id)
                .addContainerGap())
        );
        JPN_DUsuarioLayout.setVerticalGroup(
            JPN_DUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPN_DUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(JLBL_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLBL_AsignarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLBL_Tipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLBL_AsignarTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLBL_Id))
        );

        javax.swing.GroupLayout JPNL_SubfondoLayout = new javax.swing.GroupLayout(JPNL_Subfondo);
        JPNL_Subfondo.setLayout(JPNL_SubfondoLayout);
        JPNL_SubfondoLayout.setHorizontalGroup(
            JPNL_SubfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPNL_Cabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPN_DUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPNL_Slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPNL_SubfondoLayout.setVerticalGroup(
            JPNL_SubfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNL_SubfondoLayout.createSequentialGroup()
                .addComponent(JPNL_Cabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPNL_Slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPN_DUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout JPNL_FondoLayout = new javax.swing.GroupLayout(JPNL_Fondo);
        JPNL_Fondo.setLayout(JPNL_FondoLayout);
        JPNL_FondoLayout.setHorizontalGroup(
            JPNL_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNL_FondoLayout.createSequentialGroup()
                .addComponent(JPNL_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPNL_Subfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPNL_FondoLayout.setVerticalGroup(
            JPNL_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPNL_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPNL_Subfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPNL_Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPNL_Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTN_VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_VentasActionPerformed
        
    }//GEN-LAST:event_JBTN_VentasActionPerformed

    private void JBTN_AlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_AlmacenActionPerformed
       
    }//GEN-LAST:event_JBTN_AlmacenActionPerformed

    private void JBTN_CajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_CajerosActionPerformed
        
    }//GEN-LAST:event_JBTN_CajerosActionPerformed

    private void JBTN_ConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_ConfiguracionActionPerformed
        
    }//GEN-LAST:event_JBTN_ConfiguracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple JBTN_Almacen;
    private rojeru_san.RSButtonRiple JBTN_Cajeros;
    private rojeru_san.rsbutton.RSButtonRoundEffect JBTN_Cerrar;
    private rojeru_san.RSButtonRiple JBTN_Configuracion;
    private rojeru_san.rsbutton.RSButtonRoundEffect JBTN_Minimizar;
    private rojeru_san.RSButtonRiple JBTN_Ventas;
    public static javax.swing.JLabel JLBL_AsignarNombre;
    public static javax.swing.JLabel JLBL_AsignarTipo;
    public static javax.swing.JLabel JLBL_Id;
    private javax.swing.JLabel JLBL_Nombre;
    private javax.swing.JLabel JLBL_Panel;
    private javax.swing.JLabel JLBL_Tipo;
    private javax.swing.JPanel JPNL_Cabecera;
    private javax.swing.JPanel JPNL_Fondo;
    private javax.swing.JPanel JPNL_Menu;
    private rojerusan.RSPanelsSlider JPNL_Slider;
    private javax.swing.JPanel JPNL_Subfondo;
    private javax.swing.JPanel JPN_DUsuario;
    private rojerusan.RSPanelImage rSPanelImage1;
    // End of variables declaration//GEN-END:variables
}
