/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Alertas.Alerta_Error;
import Base_De_Datos.Construcciones.Usuarios;
import Base_De_Datos.Implementaciones.DAOUsuariosImpI;
import Base_De_Datos.interfaces.DAOUsuarios;
import Principal.Ventana_Principal;
import Utilidades.Cifrado;
import java.awt.Color;

/**
 *
 * @author DIEGO
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        this.setTitle("PUNTO DE VENTA CAFETERÍA - LOGIN");
        
        rsutilities.RSUtilities.setCentrarVentana(this);
        rsutilities.RSUtilities.setMoverVentana(this);
        rsutilities.RSUtilities.setOpaqueVentana(this, false);
        rsutilities.RSUtilities.setIconoVentana(this, "/IMG/Login/Icono.jpg");
    }
    
    private void Limpiar_Campos(){
        this.JTF_Usuario.requestFocus();
        this.JTF_Usuario.setNextFocusableComponent(this.JPF_Contrasena);
        
        this.JTF_Usuario.setText("");
        this.JPF_Contrasena.setText("");
    }
    
    private void Ingresar(){
        if(!this.JPF_Contrasena.getText().isEmpty() || !this.JTF_Usuario.getText().isEmpty()){
            DAOUsuarios metodosUsuarios= new DAOUsuariosImpI();
            Usuarios usuario = new Usuarios();
            
            String contrasena_cifrada = Cifrado.SHA1(JPF_Contrasena.getText());
            
            usuario.setUsuario(JTF_Usuario.getText());
            usuario.setContrasena(contrasena_cifrada);
            
            try{
                if(metodosUsuarios.Verificar_Usuario(usuario)){
                    new Thread(new Runnable() {
                        @Override
                        public void run() {
                            JBTN_Cerrar.setEnabled(false);
                            JBTN_Cerrar.setBackground(Color.WHITE);
                            JBTN_Ingresar.setEnabled(false); 
                            JTF_Usuario.setEditable(false);
                            JTF_Usuario.setBackground(Color.WHITE);
                            JPF_Contrasena.setEditable(false);
                            JPF_Contrasena.setBackground(Color.WHITE);
                            
                            Ventana_Principal VP = new Ventana_Principal();
                            VP.JLBL_AsignarNombre.setText(usuario.getNombre());
                            VP.JLBL_AsignarTipo.setText("" + usuario.getTipo());
                            VP.JLBL_Id.setText("" + usuario.getId());
                            dispose();
                            
                            VP.setVisible(true);
                        }
                    }).start();
                }else{
                    Limpiar_Campos();
            
                    Alerta_Error AE = new Alerta_Error(this,true);
                    AE.JLBL_Mensaje1.setText("El Usuario y/o Contraseña");
                    AE.JLBL_Mensaje2.setText("son incorrectos.");
                    AE.JLBL_Mensaje3.setText("");
                    AE.setVisible(true);
                } 
            }catch(Exception ex){
                Limpiar_Campos();
            
                Alerta_Error AE = new Alerta_Error(this,true);
                AE.JLBL_Mensaje1.setText("Error al establecer conexión");
                AE.JLBL_Mensaje2.setText("con la Base de Datos.");
                AE.JLBL_Mensaje3.setText("");
                AE.setVisible(true);
                
                System.out.println(ex.getMessage());
            }
        }else{
            Limpiar_Campos();
            
            Alerta_Error AE = new Alerta_Error(this,true);
            AE.JLBL_Mensaje1.setText("Ambos campos son requeridos.");
            AE.JLBL_Mensaje2.setText("");
            AE.JLBL_Mensaje3.setText("");
            AE.setVisible(true);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        jPanel1 = new javax.swing.JPanel();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        rSPanelImage2 = new rojerusan.RSPanelImage();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JPF_Contrasena = new RSMaterialComponent.RSPasswordMaterial();
        JTF_Usuario = new RSMaterialComponent.RSTextFieldMaterial();
        rSLabelImage2 = new rojerusan.RSLabelImage();
        rSLabelImage3 = new rojerusan.RSLabelImage();
        JBTN_Ingresar = new newscomponents.RSButtonFlat_new();
        JBTN_Cerrar = new rojeru_san.rsbutton.RSButtonRoundEffect();
        JLBL_Copyright1 = new javax.swing.JLabel();
        JLBL_Copyright2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/IMG/Login/Login_V1.jpg"))); // NOI18N

        rSPanelImage2.setImagen(new javax.swing.ImageIcon(getClass().getResource("/IMG/Login/Logo_PV.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage2Layout = new javax.swing.GroupLayout(rSPanelImage2);
        rSPanelImage2.setLayout(rSPanelImage2Layout);
        rSPanelImage2Layout.setHorizontalGroup(
            rSPanelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        rSPanelImage2Layout.setVerticalGroup(
            rSPanelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelImage1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(rSPanelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelImage1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(rSPanelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Aspergit", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(150, 150, 150));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOGIN");

        JPF_Contrasena.setForeground(new java.awt.Color(24, 23, 37));
        JPF_Contrasena.setColorMaterial(new java.awt.Color(66, 63, 102));
        JPF_Contrasena.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        JPF_Contrasena.setPhColor(new java.awt.Color(102, 102, 102));
        JPF_Contrasena.setPlaceholder("Ingrese su Contraseña");
        JPF_Contrasena.setSelectionColor(new java.awt.Color(66, 63, 102));
        JPF_Contrasena.setVelMils(150);

        JTF_Usuario.setForeground(new java.awt.Color(24, 23, 37));
        JTF_Usuario.setColorMaterial(new java.awt.Color(66, 63, 102));
        JTF_Usuario.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        JTF_Usuario.setPhColor(new java.awt.Color(102, 102, 102));
        JTF_Usuario.setPlaceholder("Ingrese su Usuario");
        JTF_Usuario.setSelectionColor(new java.awt.Color(66, 63, 102));
        JTF_Usuario.setVelMils(150);

        rSLabelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Login/Icono_Contrasena.png"))); // NOI18N

        rSLabelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Login/Icono_Usuario.png"))); // NOI18N

        JBTN_Ingresar.setBackground(new java.awt.Color(24, 23, 37));
        JBTN_Ingresar.setText("INGRESAR");
        JBTN_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_IngresarActionPerformed(evt);
            }
        });

        JBTN_Cerrar.setBackground(new java.awt.Color(255, 255, 255));
        JBTN_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Login/Icono_Cerrar.png"))); // NOI18N
        JBTN_Cerrar.setColorHover(new java.awt.Color(255, 255, 255));
        JBTN_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_CerrarActionPerformed(evt);
            }
        });

        JLBL_Copyright1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        JLBL_Copyright1.setForeground(new java.awt.Color(24, 23, 37));
        JLBL_Copyright1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBL_Copyright1.setText("Por favor, inicie sesión para utilizar ");

        JLBL_Copyright2.setBackground(new java.awt.Color(24, 23, 37));
        JLBL_Copyright2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        JLBL_Copyright2.setForeground(new java.awt.Color(24, 23, 37));
        JLBL_Copyright2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBL_Copyright2.setText("la aplicación");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JBTN_Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSLabelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rSLabelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JPF_Contrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(JTF_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLBL_Copyright1)
                                    .addComponent(JLBL_Copyright2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(JBTN_Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBTN_Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(82, 82, 82)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rSLabelImage3, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(JTF_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rSLabelImage2, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(JPF_Contrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(JLBL_Copyright1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLBL_Copyright2)
                .addGap(43, 43, 43)
                .addComponent(JBTN_Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rSPanelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        rSPanelShadow1.add(jPanel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTN_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_CerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JBTN_CerrarActionPerformed

    private void JBTN_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_IngresarActionPerformed
        Ingresar();
    }//GEN-LAST:event_JBTN_IngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.rsbutton.RSButtonRoundEffect JBTN_Cerrar;
    private newscomponents.RSButtonFlat_new JBTN_Ingresar;
    public static javax.swing.JLabel JLBL_Copyright1;
    public static javax.swing.JLabel JLBL_Copyright2;
    private RSMaterialComponent.RSPasswordMaterial JPF_Contrasena;
    private RSMaterialComponent.RSTextFieldMaterial JTF_Usuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private rojerusan.RSLabelImage rSLabelImage2;
    private rojerusan.RSLabelImage rSLabelImage3;
    private rojerusan.RSPanelImage rSPanelImage1;
    private rojerusan.RSPanelImage rSPanelImage2;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    // End of variables declaration//GEN-END:variables
}
